coverage:
  ignore:
    - geometric/tests/.*
    - geometric/PDB.py
    - setup.py
  status:
    patch: false
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
