# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:

  - env:
    - PYTHON_VER='2.7'

  - env:
    - PYTHON_VER='3.6'

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - if [[ "$PYTHON_VER" == "2.7" ]]; then
        conda create -q -n p4env python=$PYTHON_VER psi4 numpy=1.12 -c psi4;
    else
        conda create -q -n p4env python=$PYTHON_VER psi4 numpy=1.13 -c psi4/label/dev -c psi4;
    fi

  - source activate p4env
  - conda install scipy six netowrkx
  - conda install pytest pytest-cov codecov -c conda-forge
  - conda list

before_script:
  - python -V

script:
    # Run geometric/tests/*
  - py.test -v --cov=./

    # Hacky way to run examples
  - cd examples/water2_psi4
  - coverage run `which geometric-optimize` --psi4 water2.psi4in

after_success:
  - codecov

notifications:
  email: false

